# Site settings
title: Export Layers
site-title: Export Layers - GIMP Plug-in
email: khalim19@gmail.com
description: >
  Easily export layers as separate images in GIMP.
baseurl: "/gimp-plugin-export-layers"
url: "https://khalim19.github.io"
github_username: khalim19

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
